$ANSIBLE_VAULT;1.1;AES256
39383665376634303831313864636238343433373235306361653831376364643763316134643236
3931346131363364663339366563636264393164373565650a323865376266653338366463336133
31393333316530306637326631646530363162666263373730343363383630306365316361313562
6164313936316337350a633561323830653261383233613735653735353762366161633934616630
66613937393133313462393763656263386461363962613464373564646137313030633439666161
32613033663335396531343434633339383636336234306566356266396666663336613334636664
64393265326664376534363361653636303666313265343564323231613362343763336566393832
30343939633238663935386661346366386666623830666130626266313965616131363630643865
63656234393062303636666134346139393765623932643338356466383633373133343064333737
61326530623335353039653836383233323039633736356137663732343638643430373331656230
30333139353639313666666365653235656332333337633564363062333337636232663863323431
64646339313236396238396562323133316631343934613239376631663336663433303736323438
36363061343164353165623965316433373961363161306566343039353038616135366561303861
34326465323465346135663230336265666162633164623534303762626630663538373666653861
34393430316435663265353038643362393532613962346133663034666436353332323063373430
66396131656364613766623138396163333136376439313431336263646432613336643734373431
63633032373131643161303264373132333437393236323031663932333930323734616137386135
64393237376432646365353062626434333630613561396562626663363438643965323139636630
35623530323466316561383865313962633365653364643232323037626635396362303236333964
65623831316163386136646663303030333037626433313438363730613161333934333730373534
38343138633139646166646239626263666335666263613339616333343734613030303365373539
62373732313630666337386262663863613465313136333039303031366535336438373539396139
30373632366439333138663365336639613864363337643033313735633231623362313433373165
64306339666431666631383265636466323431626564663832366436613530623462663264323465
39313163313666353535623939383338303939366436333236303564356231336532613333333735
64663630373432343235363863313366663231633031323837363461313931633263666562666562
38623639636434663031633636393436393663303466636136383865346561346465653735376566
38643634306239636130303261346632613139393363663736633561626537396432366336633232
62336463353838356337616539326338623738626239626564333763323732653030613731373463
66326135336233663766333031383364373139653634653537306137343732613830343863353238
32383436643539336563303230323266383931653234303862663036386339636635353861623132
35303837656262643039316231383933316666663037643936646539336666643938393737393563
62393531643733356263663366343864363431353465323965373131343737653734353731373536
39656662363536333634616564626238656635626137306433366165386231363165396262376334
66666236313765666530316430613436663436366136373863333735343635616135613439303431
36653131343134386538373032313033346630313130363831313765663864663662666261343435
31633730376361363936326132316539386266633435323033663733323038366434373834353764
31323334643436356432383833313237666231373135633735666532623837323036616339653465
33353066313731373536383631343038386232623939366131353763393839316163373239333239
66373662366630613331313938623231383462323466633633386463666339663231313430303733
61623231323763633732393938663439303566646664323334366438363765353935636637323762
33643736656434326236666664323137336363616638373232616131356562373239613964383062
64333932363739323132616138356364336265666633643839643938363931303034656364353239
61393935393139613934336231613537366133343966646339313133656437643261343231613237
6334
