---
ansible_user: iliasaaguida
ansible_python_interpreter: "/home/{{ ansible_user }}/ansible_venv/bin/python"

db_table: "DOCUMENT"
db_id_field: "ID_DOCUMENT"
db_ano_text_field: "XMLA"
db_state_field: "IND_ANO"
db_state_ok: "2"
db_valid_field: "AUT_ANO"
db_titrage_table: "TITREREFERENCE"
db_table_jurica: "JCA_DECISION"
db_id_field_jurica: "JDEC_ID"
db_ano_text_field_jurica: "HTMLA"
db_state_field_jurica: "IND_ANO"
db_state_ok_jurica: "2"
db_valid_field_jurica: "AUT_ANO"
titrage_field: "_titrage"
encoding: "CP1252"
mongo_dbname: "SDER"
mongo_jurinet_collection: "rawJurinet"
mongo_jurica_collection: "rawJurica"
mongo_dila_collection: "rawDILA"
mongo_decisions_collection: "decisions"
mongo_id: "_id"
api_port: "54345"
index_db_name: "judilibre-index"
zoning_port: "8090"
zoning_protocol: "https"
zoning_normalize_source: "true"
meta_port: "8081"
meta_protocol: "http"
judifiltre_protocol: "https"

judifiltre_uri: "judifiltre.judilibre-prive.local"
meta_uri: "172.16.118.98"
zoning_uri: "nlp-jurizonage-api-service.nlp.svc.cluster.local:8090"
api_zonage_uri: "http://172.16.118.98:8090"

collection_jurinet_rawfiles: "cc-raw"
collection_jurica_rawfiles: "ca-raw"

dbsder_api_url: "http://api-service.dbsder:3000"
